CREATE CATALOG IF NOT EXISTS ow_tp;
CREATE SCHEMA IF NOT EXISTS ow_tp.bronze;
CREATE SCHEMA IF NOT EXISTS ow_tp.silver;
CREATE SCHEMA IF NOT EXISTS ow_tp.gold;
CREATE VOLUME IF NOT EXISTS ow_tp.bronze.landing;
