-- Modern schema (PostgreSQL / H2 compatible), reproducing the legacy Oracle
-- tables behind BILLING.fmb. See oracle-forms/legacy/schema/legacy_schema.sql.

CREATE TABLE IF NOT EXISTS storage_plans (
  plan_code        VARCHAR(12)   PRIMARY KEY,
  plan_name        VARCHAR(60)   NOT NULL,
  monthly_price    NUMERIC(10,2) NOT NULL,
  included_gb      INTEGER       NOT NULL,
  max_seats        INTEGER       NOT NULL,
  max_discount_pct NUMERIC(5,2)  NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS billing_customers (
  customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name  VARCHAR(100) NOT NULL,
  contact_email VARCHAR(120) NOT NULL,
  status        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     BIGINT       NOT NULL REFERENCES billing_customers (customer_id),
  plan_code       VARCHAR(12)  NOT NULL REFERENCES storage_plans (plan_code),
  seats           INTEGER      NOT NULL DEFAULT 1,
  discount_pct    NUMERIC(5,2) NOT NULL DEFAULT 0,
  start_date      DATE         NOT NULL,
  end_date        DATE,
  status          VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE'
);
