-- Run 20260927c, batch w1-lakebase-packages (units pkg_ow_util, pkg_plans, pkg_rating, pkg_invoicing).
-- Lakebase project ow-tp-billing, database ow_tp, branch mig-20260927c-w0 only.
-- Types are exactly .migration/units/<unit>/mapping_spec.json (map-20260927c-<unit>-v1); keys,
-- uniques, foreign keys and NOT NULLs follow OW_BILLING (services/legacy-billing/db/oracle/schema/01_tables.sql).
-- Reference tables billing.codes / plans / tenants / usage_events are owned by lakebase_scaffold (wave 0)
-- and are only referenced here. Idempotent by drop/recreate of the eight unit-owned tables (FK order);
-- a rerun must be followed by extract_state.py | load_state.py.

CREATE SCHEMA IF NOT EXISTS billing;

DROP TABLE IF EXISTS billing.invoice_lines;
DROP TABLE IF EXISTS billing.invoices;
DROP TABLE IF EXISTS billing.rating_results;
DROP TABLE IF EXISTS billing.rating_periods;
DROP TABLE IF EXISTS billing.credit_notes;
DROP TABLE IF EXISTS billing.subscriptions_hist;
DROP TABLE IF EXISTS billing.subscriptions;
DROP TABLE IF EXISTS billing.billing_audit_log;

-- pkg_plans ---------------------------------------------------------------------------------
CREATE TABLE billing.subscriptions (
    id           varchar(36)  NOT NULL,
    tenant_id    varchar(36)  NOT NULL,
    plan_id      varchar(36)  NOT NULL,
    starts_on    timestamp(0) NOT NULL,
    ends_on      timestamp(0),
    status_cd    bigint       NOT NULL,
    suspended_on timestamp(0),
    CONSTRAINT pk_subscriptions PRIMARY KEY (id),
    CONSTRAINT fk_sub_tenant FOREIGN KEY (tenant_id) REFERENCES billing.tenants (id),
    CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES billing.plans (id)
);

-- SEQ_SUBSCRIPTIONS_HIST + TRG_SUBSCRIPTIONS_HIST's NEXTVAL -> identity default
CREATE TABLE billing.subscriptions_hist (
    hist_id      bigint GENERATED BY DEFAULT AS IDENTITY,
    hist_dt      varchar(20),
    hist_op      varchar(3),
    id           varchar(36),
    tenant_id    varchar(36),
    plan_id      varchar(36),
    starts_on    timestamp(0),
    ends_on      timestamp(0),
    status_cd    bigint,
    suspended_on timestamp(0),
    CONSTRAINT pk_subscriptions_hist PRIMARY KEY (hist_id)
);

-- pkg_rating ---------------------------------------------------------------------------------
CREATE TABLE billing.rating_periods (
    id           varchar(36)  NOT NULL,
    tenant_id    varchar(36)  NOT NULL,
    period_start timestamp(0) NOT NULL,
    period_end   timestamp(0) NOT NULL,
    CONSTRAINT pk_rating_periods PRIMARY KEY (id),
    CONSTRAINT uq_rating_periods UNIQUE (tenant_id, period_start),
    CONSTRAINT fk_rp_tenant FOREIGN KEY (tenant_id) REFERENCES billing.tenants (id)
);

CREATE TABLE billing.rating_results (
    id              varchar(36)   NOT NULL,
    period_id       varchar(36)   NOT NULL,
    subscription_id varchar(36)   NOT NULL,
    used_units      bigint        NOT NULL,
    quota_units     bigint        NOT NULL,
    rollover_units  bigint        NOT NULL,
    billable_units  bigint        NOT NULL,
    overage_amount  numeric(12,2) NOT NULL,
    created_at      timestamp(6)  NOT NULL,
    CONSTRAINT pk_rating_results PRIMARY KEY (id),
    CONSTRAINT fk_rr_period FOREIGN KEY (period_id) REFERENCES billing.rating_periods (id),
    CONSTRAINT fk_rr_sub FOREIGN KEY (subscription_id) REFERENCES billing.subscriptions (id)
);

-- pkg_invoicing ------------------------------------------------------------------------------
CREATE TABLE billing.invoices (
    id        varchar(36)   NOT NULL,
    tenant_id varchar(36)   NOT NULL,
    period_id varchar(36)   NOT NULL,
    issued_at timestamp(6)  NOT NULL,
    subtotal  numeric(12,2) NOT NULL,
    tax       numeric(12,2) NOT NULL,
    total     numeric(12,2) NOT NULL,
    status_cd bigint        NOT NULL,
    CONSTRAINT pk_invoices PRIMARY KEY (id),
    CONSTRAINT fk_inv_tenant FOREIGN KEY (tenant_id) REFERENCES billing.tenants (id),
    CONSTRAINT fk_inv_period FOREIGN KEY (period_id) REFERENCES billing.rating_periods (id)
);

CREATE TABLE billing.invoice_lines (
    id          varchar(36)   NOT NULL,
    invoice_id  varchar(36)   NOT NULL,
    line_no     bigint        NOT NULL,
    line_type   varchar(10)   NOT NULL,
    description varchar(400)  NOT NULL,
    amount      numeric(12,2) NOT NULL,
    CONSTRAINT pk_invoice_lines PRIMARY KEY (id),
    CONSTRAINT uq_invoice_lines UNIQUE (invoice_id, line_no),
    CONSTRAINT fk_il_invoice FOREIGN KEY (invoice_id) REFERENCES billing.invoices (id) ON DELETE CASCADE
);

CREATE TABLE billing.credit_notes (
    id               varchar(36)   NOT NULL,
    tenant_id        varchar(36)   NOT NULL,
    issued_on        timestamp(0)  NOT NULL,
    amount           numeric(12,2) NOT NULL,
    remaining_amount numeric(12,2) NOT NULL,
    CONSTRAINT pk_credit_notes PRIMARY KEY (id),
    CONSTRAINT fk_cn_tenant FOREIGN KEY (tenant_id) REFERENCES billing.tenants (id)
);

-- pkg_ow_util --------------------------------------------------------------------------------
-- SEQ_BILLING_AUDIT_LOG + TRG_BILLING_AUDIT_LOG_ID -> identity default (D-009: logged_at not graded)
CREATE TABLE billing.billing_audit_log (
    log_id    bigint GENERATED BY DEFAULT AS IDENTITY,
    logged_at timestamp(0) NOT NULL DEFAULT date_trunc('second', localtimestamp),
    module    varchar(30),
    message   varchar(4000),
    CONSTRAINT pk_billing_audit_log PRIMARY KEY (log_id)
);
