-- Legacy Oracle schema behind the BILLING.fmb Forms application.
-- Reference only: the modern target reproduces this schema in PostgreSQL/H2.
-- Oracle DDL (as it existed in the legacy database).

CREATE TABLE STORAGE_PLANS (
  PLAN_CODE        VARCHAR2(12)  NOT NULL,
  PLAN_NAME        VARCHAR2(60)  NOT NULL,
  MONTHLY_PRICE    NUMBER(10,2)  NOT NULL,
  INCLUDED_GB      NUMBER(10)    NOT NULL,
  MAX_SEATS        NUMBER(6)     NOT NULL,
  MAX_DISCOUNT_PCT NUMBER(5,2)   DEFAULT 0 NOT NULL,
  CONSTRAINT PK_STORAGE_PLANS PRIMARY KEY (PLAN_CODE)
);

CREATE TABLE BILLING_CUSTOMERS (
  CUSTOMER_ID   NUMBER(10)    NOT NULL,
  COMPANY_NAME  VARCHAR2(100) NOT NULL,
  CONTACT_EMAIL VARCHAR2(120) NOT NULL,
  STATUS        VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT    DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_BILLING_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
  CONSTRAINT CK_CUSTOMER_STATUS CHECK (STATUS IN ('ACTIVE','SUSPENDED','CLOSED'))
);

CREATE TABLE SUBSCRIPTIONS (
  SUBSCRIPTION_ID NUMBER(10)   NOT NULL,
  CUSTOMER_ID     NUMBER(10)   NOT NULL,
  PLAN_CODE       VARCHAR2(12) NOT NULL,
  SEATS           NUMBER(6)    DEFAULT 1 NOT NULL,
  DISCOUNT_PCT    NUMBER(5,2)  DEFAULT 0 NOT NULL,
  START_DATE      DATE         NOT NULL,
  END_DATE        DATE,
  STATUS          VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT PK_SUBSCRIPTIONS PRIMARY KEY (SUBSCRIPTION_ID),
  CONSTRAINT FK_SUB_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES BILLING_CUSTOMERS (CUSTOMER_ID),
  CONSTRAINT FK_SUB_PLAN FOREIGN KEY (PLAN_CODE) REFERENCES STORAGE_PLANS (PLAN_CODE),
  CONSTRAINT CK_SUB_STATUS CHECK (STATUS IN ('ACTIVE','CANCELLED'))
);

-- Seed plans (the reference data the LOV reads and the triggers validate against)
INSERT INTO STORAGE_PLANS VALUES ('FREE',       'Free',       0,     15,   1,   0);
INSERT INTO STORAGE_PLANS VALUES ('BASIC',      'Basic',      9.99,  100,  5,   0);
INSERT INTO STORAGE_PLANS VALUES ('PRO',        'Pro',        29.99, 1000, 25,  0);
INSERT INTO STORAGE_PLANS VALUES ('ENTERPRISE', 'Enterprise', 99.99, 10000, 500, 20);
