#!/usr/bin/env python3
"""Unit p1-billing-audit-log (U-19), write half: ow_tp.silver.billing_audit_log.

Analytical track. The table is the sink of `pkg_ow_util.log_msg`'s autonomous transaction
(converted in wave 0 under P1-D1); this unit owns the table itself and the identity the
legacy `seq_billing_audit_log` + `trg_billing_audit_log_id` pair provides.

What the converted table keeps:

  - `log_id` is `GENERATED BY DEFAULT AS IDENTITY`. The trigger assigned the sequence only
    when the insert left `log_id` NULL and honoured an explicit value otherwise, which is
    exactly the `BY DEFAULT` contract. After a load that carries explicit keys the identity
    is re-synced, or the next generated value collides with a loaded one.
  - `logged_at` is `TIMESTAMP_NTZ`. The source column is an Oracle `DATE`: it carries a
    time part and no zone, and Databricks `TIMESTAMP` is a zoned instant that compares
    unequal to the same wall-clock value. The mapping spec declares `TIMESTAMP`; that file
    is parent-owned, so the rule is applied here and raised as dialect feedback instead.
  - `module` and `message` keep the mapping's `empty_string_is_null` rule, so an Oracle
    empty string (which is NULL in Oracle) stays NULL here.
  - No foreign key is added: the legacy table has none, and the audit rows are written by
    an autonomous transaction that can outlive a rolled-back caller, so a key to any other
    table would reject rows the source accepts.

The snapshot comes from `billing_audit_log_extract.py`, which is where the one legacy read
happens; this program never holds a legacy credential. The snapshot is complete, so the
MERGE deletes keys the source no longer has and a rerun converges instead of duplicating.
The source is empty today, so this run establishes schema parity and an empty target - it
proves nothing about data, and the unit's recon records that as NOT DATA-PROVEN.

`--digest-out` writes a target-state digest (row count plus an order-independent content
hash, read back from the target). Two digests from two runs are the idempotency evidence.

usage (with DATABRICKS_HOST / DATABRICKS_CLIENT_ID / DATABRICKS_CLIENT_SECRET set):
  python3 databricks/migration/silver/billing_audit_log_load.py --parquet /tmp/bal.parquet
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import uuid
from pathlib import Path

from databricks import sql as dbsql
from databricks.sdk import WorkspaceClient

CATALOG = "ow_tp"
SCHEMA = "silver"
TABLE = "billing_audit_log"
TARGET = f"{CATALOG}.{SCHEMA}.{TABLE}"
VOLUME = "/Volumes/ow_tp/bronze/landing"
WAREHOUSE = "565cd2fd713738c4"

DDL = f"""CREATE TABLE IF NOT EXISTS {TARGET} (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL
    COMMENT 'legacy BILLING_AUDIT_LOG.LOG_ID, NUMBER(12); seq_billing_audit_log + trg_billing_audit_log_id assigned it only when the insert left it NULL',
  logged_at TIMESTAMP_NTZ NOT NULL
    COMMENT 'legacy BILLING_AUDIT_LOG.LOGGED_AT, DATE DEFAULT SYSDATE; the source carries no zone and keeps its time part, UTC is assumed and declared (plan decision P1-D3)',
  module STRING COMMENT 'legacy BILLING_AUDIT_LOG.MODULE, VARCHAR2(30)',
  message STRING COMMENT 'legacy BILLING_AUDIT_LOG.MESSAGE, VARCHAR2(4000)'
)
USING DELTA
COMMENT 'U-19 BILLING_AUDIT_LOG from the legacy billing estate; written by pkg_ow_util.log_msg and purged by the ow_tp_p1_purge_audit_log job. Loaded by databricks/migration/silver/billing_audit_log_load.py'"""

DEFAULT_LOGGED_AT = (f"ALTER TABLE {TARGET} ALTER COLUMN logged_at "
                     "SET DEFAULT current_timestamp()")
ALLOW_DEFAULTS = (f"ALTER TABLE {TARGET} SET TBLPROPERTIES "
                  "('delta.feature.allowColumnDefaults' = 'supported')")
PRIMARY_KEY = (f"ALTER TABLE {TARGET} ADD CONSTRAINT pk_billing_audit_log "
               "PRIMARY KEY (log_id)")
SYNC_IDENTITY = f"ALTER TABLE {TARGET} ALTER COLUMN log_id SYNC IDENTITY"

MERGE = f"""MERGE INTO {TARGET} t USING (
  SELECT CAST(log_id AS BIGINT) AS log_id,
         CAST(logged_at AS TIMESTAMP_NTZ) AS logged_at,
         NULLIF(CAST(module AS STRING), '') AS module,
         NULLIF(CAST(message AS STRING), '') AS message
  FROM parquet.`{{staged}}`) s
ON t.log_id = s.log_id
WHEN MATCHED THEN UPDATE SET t.logged_at = s.logged_at, t.module = s.module,
                             t.message = s.message
WHEN NOT MATCHED THEN INSERT (log_id, logged_at, module, message)
  VALUES (s.log_id, s.logged_at, s.module, s.message)
WHEN NOT MATCHED BY SOURCE THEN DELETE"""

# Order-independent: the per-row hashes are sorted before they are folded, so the digest
# depends on the set of rows and not on the order Delta returns them in.
DIGEST = ("SELECT count(*), sha2(array_join(array_sort(collect_list(row_hash)), ''), 256) "
          f"FROM (SELECT sha2(to_json(struct(*)), 256) AS row_hash FROM {TARGET})")


def sql_conn():
    from databricks.sdk.core import Config, oauth_service_principal

    cfg = Config(host=os.environ["DATABRICKS_HOST"],
                 client_id=os.environ["DATABRICKS_CLIENT_ID"],
                 client_secret=os.environ["DATABRICKS_CLIENT_SECRET"])
    return dbsql.connect(
        server_hostname=os.environ["DATABRICKS_HOST"].replace("https://", ""),
        http_path=f"/sql/1.0/warehouses/{WAREHOUSE}",
        credentials_provider=lambda: oauth_service_principal(cfg))


def ensure_table(cur) -> None:
    cur.execute(DDL)
    cur.execute(ALLOW_DEFAULTS)
    # `logged_at DATE DEFAULT SYSDATE` in the source: a writer that omits the column still
    # gets the insert time.
    cur.execute(DEFAULT_LOGGED_AT)
    cur.execute(f"SELECT count(*) FROM {TARGET}")


def ensure_primary_key(cur) -> bool:
    """The legacy `pk_billing_audit_log`, as an informational Unity Catalog key."""
    cur.execute(f"SELECT count(*) FROM {CATALOG}.information_schema.table_constraints "
                f"WHERE table_schema = '{SCHEMA}' AND table_name = '{TABLE}' "
                "AND constraint_type = 'PRIMARY KEY'")
    if cur.fetchone()[0]:
        return False
    cur.execute(PRIMARY_KEY)
    return True


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--parquet", type=Path, required=True,
                    help="snapshot written by billing_audit_log_extract.py")
    ap.add_argument("--digest-out", type=Path,
                    help="write this run's target-state digest here, as rerun evidence")
    args = ap.parse_args(argv)

    run_id = uuid.uuid4().hex
    staged = f"{VOLUME}/{TABLE}/{run_id}.parquet"
    workspace = WorkspaceClient()
    with args.parquet.open("rb") as handle:
        workspace.files.upload(staged, handle, overwrite=True)
    try:
        with sql_conn() as conn, conn.cursor() as cur:
            ensure_table(cur)
            key_added = ensure_primary_key(cur)
            cur.execute(MERGE.format(staged=staged))
            # A loaded explicit key is above the identity's high-water mark until it is
            # re-synced; without this the next generated log_id collides with a loaded row.
            cur.execute(SYNC_IDENTITY)
            cur.execute(f"SELECT count(*), count(DISTINCT log_id) FROM {TARGET}")
            rows, keys = cur.fetchone()
            if rows != keys:
                raise SystemExit(f"{TARGET} holds {rows} rows for {keys} distinct log_id")
            digest = None
            if args.digest_out:
                cur.execute(DIGEST)
                digest_rows, content = cur.fetchone()
                digest = {"rows": digest_rows, "content_digest": content}
    finally:
        workspace.files.delete(staged)

    if args.digest_out:
        finished = dt.datetime.now(dt.timezone.utc).isoformat(timespec="microseconds")
        args.digest_out.parent.mkdir(parents=True, exist_ok=True)
        args.digest_out.write_text(json.dumps(
            {"kind": "target-state-digest", "unit": "p1-billing-audit-log",
             "run_id": run_id, "finished_at": finished,
             "tables": [{"table": TARGET, **digest}]}, indent=2) + "\n")

    print(json.dumps({"table": TARGET, "snapshot": str(args.parquet),
                      "target_rows": rows, "deletes_converged": True,
                      "primary_key_added": key_added, "identity_synced": True,
                      "digest": digest, "staged_retained": False}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
