akka {
  loglevel = "INFO"
  http {
    server {
      idle-timeout = 60s
      request-timeout = 30s
    }
  }
}

analytics {
  s3 {
    data-lake-bucket = "otterworks-data-lake"
    data-lake-bucket = ${?S3_DATA_LAKE_BUCKET}
  }
  sqs {
    events-queue-url = "http://localhost:4566/000000000000/otterworks-analytics-events"
    events-queue-url = ${?SQS_ANALYTICS_QUEUE_URL}
  }
  aws {
    region = "us-east-1"
    region = ${?AWS_REGION}
    endpoint-url = ${?AWS_ENDPOINT_URL}
  }
}
