#!/usr/bin/env python3
"""dbx-parse: the converted CUSTBILL fixed-width parse on Databricks.

Replaces etl/legacy-extra/jobs/parse_custbill_fixedwidth.sh with a single
validating pass that lands its own drops on the bronze volume and writes a typed
silver table plus a quarantine table. Namespace-scoped throughout (`--ns`): the
demo workspace is shared, so nothing here creates a catalog, schema, volume or
compute, and every table it touches carries its own namespace suffix.

  land      upload this namespace's CUSTBILL drops into the landing volume
  provision create this namespace's own silver + quarantine tables
  deploy    import the notebook and upsert the (manually triggered) job
  run       trigger the job and report the run URL and outcome
  status    summarise what exists in this namespace
  fixture   run the same parse locally over the golden drops (no Databricks)
  teardown  drop this namespace's own tables and landed files

Landing is marker-based: a stale sibling `<name>.ok` marker is removed before
each `.dat` upload, then the marker is uploaded second, and the job only
consumes a `.dat` that has its marker. The Files API has no rename, so the
marker — not a rename — is what makes a half-uploaded drop invisible to the
parse.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import parse_sql as S
from client import Databricks, DbxError, require_ident, require_ns
from custbill_layout import parse_file

REPO = Path(__file__).resolve().parents[2]
NOTEBOOK_EPILOGUE = '''

# COMMAND ----------

# Databricks entry point: parse every marked drop in this namespace's landing
# slice into the namespace's own silver and quarantine tables. Per-file replace
# makes a rerun idempotent; an empty slice is a no-op that leaves prior output
# intact (the legacy chain's "just rerun everything" entry could erase a day).
import json
import os

dbutils.widgets.text("ns", "demo")
dbutils.widgets.text("catalog", "ow_tp")
names = Names(catalog=dbutils.widgets.get("catalog"), ns=dbutils.widgets.get("ns"))

for statement in ddl(names):
    spark.sql(statement)

try:
    entries = sorted(os.listdir(names.incoming))
except FileNotFoundError:
    entries = []
present = set(entries)
drops = [e for e in entries if e.endswith(".dat") and e + ".ok" in present]
unmarked = [e for e in entries if e.endswith(".dat") and e + ".ok" not in present]

summary = {"ns": names.ns, "files": [], "skipped_unmarked": unmarked,
           "records": 0, "rejects": 0, "failed_files": []}
for name in drops:
    with open(names.incoming + "/" + name, "rb") as handle:
        data = handle.read()
    result = parse_file(name, data)
    for statement, params in delete_file_rows(names, name):
        spark.sql(statement, args=params)
    for statement, params in insert_records(names, result.records):
        spark.sql(statement, args=params)
    for statement, params in insert_rejects(names, result.rejects):
        spark.sql(statement, args=params)
    summary["files"].append({
        "file": name, "body_lines": result.body_count, "trailer": result.trailer_count,
        "records": len(result.records), "rejects": len(result.rejects), "failed": result.failed,
    })
    summary["records"] += len(result.records)
    summary["rejects"] += len(result.rejects)
    if result.failed:
        summary["failed_files"].append(name)

print(json.dumps(summary, indent=2))
dbutils.notebook.exit(json.dumps(summary))
'''


def names_for(args) -> S.Names:
    return S.Names(catalog=require_ident(args.catalog, "catalog"), ns=require_ns(args.ns))


def notebook_source() -> str:
    """The notebook is generated from the repo modules so the parse that runs in
    Databricks is the same text the local fixture harness verifies."""
    here = Path(__file__).resolve().parent
    parts = ["# Databricks notebook source",
             "# Generated by scripts/tp_dbx/parse_unit.py deploy — edit the modules, not the notebook."]
    for module in ("custbill_layout.py", "parse_sql.py"):
        body = (here / module).read_text()
        parts.append("\n# COMMAND ----------\n\n# --- " + module + " ---\n" + body)
    parts.append(NOTEBOOK_EPILOGUE)
    return "\n".join(parts)


def legacy_root() -> Path:
    return Path(os.environ.get("OTTERWORKS_LEGACY_ROOT", "/tmp/otterworks-legacy"))


def local_drops(source_dir: Path) -> list:
    drops = sorted(p for p in source_dir.glob("CUSTBILL*.dat"))
    if not drops:
        # the legacy parse renames what it consumed; the archive keeps the bytes
        drops = sorted(source_dir.glob("CUSTBILL*.dat.done"))
    return drops


def cmd_land(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    source_dir = Path(args.source) if args.source else legacy_root() / "incoming"
    drops = local_drops(source_dir)
    if not drops:
        raise SystemExit(f"no CUSTBILL drops found under {source_dir}")
    for drop in drops:
        name = drop.name.removesuffix(".done")
        payload = drop.read_bytes()
        dbx.delete_file(f"{n.incoming}/{name}.ok")
        dbx.put_file(f"{n.incoming}/{name}", payload)
        dbx.put_file(f"{n.incoming}/{name}.ok", b"")
        print(f"landed {name} ({len(payload)} bytes) -> {n.incoming}/{name}")
    return 0


def cmd_provision(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    for statement in S.ddl(n):
        dbx.sql_ok(statement)
    print(f"provisioned {n.silver} and {n.quarantine}")
    return 0


def cmd_deploy(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    dbx.import_notebook(n.notebook, notebook_source())
    settings = {
        "name": n.job,
        "max_concurrent_runs": 1,
        "parameters": [{"name": "ns", "default": n.ns}, {"name": "catalog", "default": n.catalog}],
        "tasks": [{
            "task_key": "parse_custbill",
            "notebook_task": {
                "notebook_path": n.notebook,
                "base_parameters": {"ns": n.ns, "catalog": n.catalog},
            },
        }],
        "tags": {"project": "otterworks-tp", "unit": "dbx-parse", "ns": n.ns},
    }
    job_id = dbx.upsert_job(settings)
    print(json.dumps({"job": n.job, "job_id": job_id, "notebook": n.notebook,
                      "url": f"{dbx.host}/jobs/{job_id}", "schedule": "none (manual trigger only)"}, indent=2))
    return 0


def cmd_run(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    job = dbx.find_job(n.job)
    if not job:
        raise SystemExit(f"job {n.job} does not exist; run deploy first")
    run_id = dbx.run_job(int(job["job_id"]))
    print(f"run url: {dbx.run_url(run_id)}")
    run = dbx.wait_run(run_id)
    state = run.get("state", {})
    output = ""
    for task in run.get("tasks", []):
        payload = dbx.ok("GET", f"/api/2.1/jobs/runs/get-output?run_id={task['run_id']}")
        output = payload.get("notebook_output", {}).get("result", "") or payload.get("error", "")
    print(json.dumps({"run_id": run_id, "result_state": state.get("result_state"),
                      "url": dbx.run_url(run_id), "output": output}, indent=2))
    if state.get("result_state") != "SUCCESS":
        return 1
    return 0


def cmd_status(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    counts = dbx.sql_ok(S.counts(n)).dicts()
    job = dbx.find_job(n.job)
    print(json.dumps({
        "ns": n.ns,
        "silver": n.silver,
        "quarantine": n.quarantine,
        "counts": counts,
        "landed": [item.get("name") for item in dbx.list_dir(n.incoming)],
        "job_id": job and job.get("job_id"),
    }, indent=2, default=str))
    return 0


def cmd_fixture(args) -> int:
    """Local, Databricks-free run of the same parse over the golden drops."""
    source_dir = Path(args.source) if args.source else legacy_root() / "incoming"
    report = {"mode": "fixture", "source_dir": str(source_dir), "files": []}
    for drop in local_drops(source_dir):
        name = drop.name.removesuffix(".done")
        result = parse_file(name, drop.read_bytes())
        report["files"].append({
            "file": name, "body_lines": result.body_count, "trailer": result.trailer_count,
            "records": len(result.records), "rejects": len(result.rejects), "failed": result.failed,
            "reasons": sorted({reject.reason_code for reject in result.rejects}),
        })
    print(json.dumps(report, indent=2))
    return 0


def cmd_teardown(args) -> int:
    n = names_for(args)
    dbx = Databricks(warehouse_id=args.warehouse)
    for table in (n.silver, n.quarantine):
        dbx.sql_ok(f"DROP TABLE IF EXISTS {table}")
        print(f"dropped {table}")
    for item in dbx.list_dir(n.incoming):
        dbx.delete_file(item["path"])
    dbx.delete_dir(n.incoming)
    dbx.delete_dir(n.landing)
    status, _ = dbx.call("POST", "/api/2.0/workspace/delete", {"path": n.notebook})
    print(f"workspace delete {n.notebook}: HTTP {status}")
    job = dbx.find_job(n.job)
    if job:
        dbx.ok("POST", "/api/2.1/jobs/delete", {"job_id": int(job["job_id"])})
        print(f"deleted job {n.job}")
    return 0


COMMANDS = {
    "land": cmd_land, "provision": cmd_provision, "deploy": cmd_deploy, "run": cmd_run,
    "status": cmd_status, "fixture": cmd_fixture, "teardown": cmd_teardown,
}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=sorted(COMMANDS))
    parser.add_argument("--ns", default="demo", help="demo namespace (own slice only)")
    parser.add_argument("--catalog", default="ow_tp")
    parser.add_argument("--warehouse", default=os.environ.get("DATABRICKS_SQL_WAREHOUSE_ID", ""))
    parser.add_argument("--source", default="", help="directory of CUSTBILL drops (default $OTTERWORKS_LEGACY_ROOT/incoming)")
    args = parser.parse_args(argv)
    try:
        return COMMANDS[args.command](args)
    except DbxError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
