-- Wave 0, batch w0-a: pkg_ow_util converted to PL/pgSQL, plus the wave-0 scaffolding the
-- later waves code against.
--
-- Source: services/legacy-billing/db/oracle/packages/01_pkg_util.sql (read-only).
-- Target: Lakebase project ow-tp-billing, database ow_tp, schema billing, on the wave branch.
-- Idempotent: every statement is CREATE ... IF NOT EXISTS or CREATE OR REPLACE (P1-D6).
--
-- Package state (g_call_count, g_last_module, g_last_uuid) is NOT reproduced as hidden
-- session state. Oracle's globals here are write-only bookkeeping: no caller reads them
-- (verified across the four packages), so they become the audit-log row that log_msg already
-- writes rather than a table nobody queries. The state that IS read across packages -
-- pkg_rating's g_overage_amount - becomes billing.rating_state below (P1-D4).

CREATE SCHEMA IF NOT EXISTS billing;

-- f_md5_uuid: MD5 of the UTF-8 bytes, lowercase hex, hyphenated 8-4-4-4-12. Oracle's
-- STANDARD_HASH(UTL_RAW.CAST_TO_RAW(x),'MD5') hashes the raw bytes of the string, which is
-- what Postgres md5(text) does on a UTF-8 database. NULL in, NULL out (Oracle returns NULL
-- because SUBSTR of NULL is NULL); empty string is NOT null here, unlike Oracle, so it is in
-- the parity vector explicitly - see the D2-01 note in the unit's summary.
CREATE OR REPLACE FUNCTION billing.f_md5_uuid(p_input text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE WHEN p_input IS NULL THEN NULL ELSE
        substr(md5(p_input), 1, 8)  || '-' ||
        substr(md5(p_input), 9, 4)  || '-' ||
        substr(md5(p_input), 13, 4) || '-' ||
        substr(md5(p_input), 17, 4) || '-' ||
        substr(md5(p_input), 21, 12)
    END
$$;

-- f_code_desc: the Oracle version wraps a static lookup in EXECUTE IMMEDIATE. Converted to a
-- plain query. NO_DATA_FOUND -> 'UNKNOWN(<val>)' with NVL(p_val,-1), reproduced exactly,
-- including the -1 for a NULL code value.
CREATE OR REPLACE FUNCTION billing.f_code_desc(p_type text, p_val numeric)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_desc text;
BEGIN
    SELECT code_desc INTO v_desc
      FROM billing.codes
     WHERE code_type = p_type AND code_val = p_val;
    IF NOT FOUND THEN
        RETURN 'UNKNOWN(' || COALESCE(p_val, -1)::text || ')';
    END IF;
    RETURN v_desc;
END;
$$;

-- f_dt2str: 'DD-MON-YY' with English month abbreviations, upper case, as Oracle's
-- NLS_DATE_LANGUAGE=ENGLISH gives. to_char pads MON to a fixed width, so FM is required to
-- match Oracle byte-for-byte.
CREATE OR REPLACE FUNCTION billing.f_dt2str(p_dt date)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE WHEN p_dt IS NULL THEN NULL
                ELSE to_char(p_dt, 'FMDD-MON-YY') END
$$;

-- f_str2dt: returns NULL on anything unparseable, silently. That is contract, not a bug
-- (P1-D2): the malformed dates are a declared anomaly set and the report surfaces depend on
-- the NULL. Postgres raises instead of returning NULL, so the exception is caught.
CREATE OR REPLACE FUNCTION billing.f_str2dt(p_str text)
RETURNS date
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    RETURN to_date(p_str, 'DD-MON-YY');
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END;
$$;

-- billing_audit_log: written by log_msg's autonomous transaction. This unit owns the
-- operational copy; ow_tp.silver.billing_audit_log (U-19) is the analytical copy.
CREATE TABLE IF NOT EXISTS billing.billing_audit_log (
    log_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module     varchar(30),
    message    varchar(4000),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- log_msg: Oracle's PRAGMA AUTONOMOUS_TRANSACTION commits the log row even when the caller
-- rolls back, and swallows its own failures (P1-D1). Postgres has no autonomous transaction,
-- so the write goes through a dblink-free best-effort path: it is a separate function the
-- caller invokes, wrapped so it can never fail the caller. The commit-independence half is
-- NOT reproducible inside one Postgres backend and is a declared behaviour difference:
-- a caller that rolls back loses its log rows. Recorded in the unit's summary as an
-- unverified/divergent path, not papered over.
CREATE OR REPLACE FUNCTION billing.log_msg(p_module text, p_message text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO billing.billing_audit_log (module, message)
    VALUES (left(p_module, 30), left(p_message, 4000));
EXCEPTION
    WHEN OTHERS THEN
        NULL;  -- swallowed, exactly as Oracle does
END;
$$;

-- rating_state: the explicit pkg_rating -> pkg_invoicing hand-off that replaces Oracle's
-- mutable package global g_overage_amount (P1-D4). Wave 3 codes against this shape: w3-a
-- writes it, w3-b reads it, concurrently.
CREATE TABLE IF NOT EXISTS billing.rating_state (
    tenant_id      text        NOT NULL,
    period_id      text        NOT NULL,
    overage_amount numeric(18, 2),
    finalized      boolean     NOT NULL DEFAULT false,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, period_id)
);

-- md5_parity_input: the seed table the three MD5 parity ops compare against. Seeded over the
-- read-only JDBC path with the exact inputs Oracle used for the ids it already stores.
CREATE TABLE IF NOT EXISTS billing.md5_parity_input (
    vector text NOT NULL,
    input  text,
    PRIMARY KEY (vector, input)
);
