-- U-13 ENTITY_ATTR_VALUE -> Lakebase billing.entity_attr_value (unit p1-entity-attr-value,
-- wave 2 batch c).
--
-- Oracle source: OW_BILLING.ENTITY_ATTR_VALUE
-- (services/legacy-billing/db/oracle/schema/02_horror.sql). The table is the estate's
-- entity-attribute-value dumping ground: every value is a string, whatever it means.
-- Pipeline 1 promotes nothing - ATTR_VALUE stays varchar(4000), so a row holding '12.50' or
-- 'TRUE' arrives byte-identical and any typing stays where it is today, in the reading code.
--
-- Only EAV_ID is a key. Two rows carrying the same (ENTITY_TYPE, ENTITY_ID, ATTR_NAME) are
-- legal in Oracle and stay legal here: no unique constraint is added, so duplicate-attribute
-- rows survive as a set. No foreign key points at the entity either - ENTITY_ID is a free
-- text column referring to whatever ENTITY_TYPE names, and adding one would reject the
-- orphan rows D8-01 requires us to reproduce.
--
-- SEQ_ENTITY_ATTR_VALUE and TRG_ENTITY_ATTR_VALUE_SEQ convert with the table: the trigger
-- fills EAV_ID from the sequence only when the insert leaves it NULL, which is exactly
-- GENERATED BY DEFAULT AS IDENTITY. The sequence's START/INCREMENT/CACHE are carried over so
-- the identity behaves like the source's, including the gaps CACHE 1000 leaves behind.
-- NUMBER(14) is outside int4's range, so the key is bigint.
--
-- CREATED_DT is one of the 37 'DD-MON-YY' string-date columns: the raw string migrates
-- byte-exact as varchar(9), and consumers get a parsed companion. CREATED_DT_PARSED is a
-- stored generated column over billing.f_str2dt (wave 0), which returns NULL on anything
-- unparseable - that NULL is the legacy behaviour and is part of the declared anomaly set.
-- It is timestamp, not date: an Oracle DATE carries a time part, and a parsed companion that
-- dropped it would compare unequal to the source the first time a value is not midnight.

CREATE SCHEMA IF NOT EXISTS billing;

CREATE TABLE IF NOT EXISTS billing.entity_attr_value (
    eav_id      bigint       GENERATED BY DEFAULT AS IDENTITY
                             (START WITH 1 INCREMENT BY 1 CACHE 1000),
    entity_type varchar(30)  NOT NULL,
    entity_id   varchar(36)  NOT NULL,
    attr_name   varchar(100) NOT NULL,
    attr_value  varchar(4000),
    attr_type   varchar(10)  DEFAULT 'STR',
    created_dt  varchar(9),
    created_dt_parsed timestamp
        GENERATED ALWAYS AS (billing.f_str2dt(created_dt)::timestamp) STORED,
    CONSTRAINT pk_entity_attr_value PRIMARY KEY (eav_id)
);

COMMENT ON TABLE billing.entity_attr_value IS
    'Migration unit p1-entity-attr-value (U-13) from Oracle OW_BILLING.ENTITY_ATTR_VALUE.';
COMMENT ON COLUMN billing.entity_attr_value.attr_value IS
    'Untyped legacy value; pipeline 1 promotes no types - the string is carried as written.';
COMMENT ON COLUMN billing.entity_attr_value.created_dt IS
    'Raw DD-MON-YY string, byte-exact from the source, malformed values included.';
COMMENT ON COLUMN billing.entity_attr_value.created_dt_parsed IS
    'billing.f_str2dt(created_dt); NULL where the raw string does not parse (declared anomaly).';
