source 'https://rubygems.org'
ruby '~> 3.4.0'

gem 'active_model_serializers', '~> 0.10'
gem 'bootsnap', require: false
gem 'jbuilder', '~> 2.15'
gem 'jwt', '~> 3.2'
gem 'kaminari', '~> 1.2'
gem 'pg', '~> 1.6'
gem 'puma', '~> 8.0'
gem 'rack-attack', '~> 6.8'
gem 'rack-cors', '~> 3.0'
gem 'rails', '~> 8.1.3'
gem 'redis', '~> 6.0'
gem 'sidekiq', '~> 8.1'

# Observability
gem 'lograge', '~> 0.15'
gem 'opentelemetry-instrumentation-rails', '~> 0.42'
gem 'opentelemetry-sdk', '~> 1.13'
gem 'prometheus_exporter', '~> 2.3'

group :development, :test do
  gem 'debug', platforms: %i[mri]
  gem 'factory_bot_rails', '~> 6.5'
  gem 'faker', '~> 3.8'
  gem 'rspec-rails', '~> 8.0'
  gem 'rubocop', '~> 1.89', require: false
  gem 'rubocop-rails', '~> 2.36', require: false
  gem 'rubocop-rspec', '~> 3.10', require: false
end

group :test do
  gem 'database_cleaner-active_record', '~> 2.2'
  gem 'shoulda-matchers', '~> 8.0'
  # simplecov 1.x requires Ruby >= 3.4
  gem 'simplecov', '~> 0.22', require: false
end
