source "https://rubygems.org"
ruby "~> 3.3.0"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "activeadmin", "~> 3.2"
gem "devise", "~> 4.9"
gem "pundit", "~> 2.3"
gem "sidekiq", "~> 7.2"
gem "redis", "~> 5.1"
gem "jbuilder", "~> 2.11"
gem "rack-cors", "~> 2.0"
gem "bootsnap", require: false

# Observability
gem "prometheus_exporter", "~> 2.1"
gem "opentelemetry-sdk", "~> 1.4"
gem "opentelemetry-instrumentation-rails", "~> 0.30"
gem "lograge", "~> 0.14"

group :development, :test do
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.3"
  gem "rubocop-rails", "~> 2.24", require: false
  gem "debug", platforms: %i[mri]
end

group :test do
  gem "shoulda-matchers", "~> 6.1"
  gem "simplecov", require: false
end
