-- Creates the OW_BILLING schema owner inside the FREEPDB1 pluggable
-- database. Run as SYSTEM against FREEPDB1.
WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER ow_billing IDENTIFIED BY ow_billing
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE,
      CREATE TRIGGER, CREATE VIEW, CREATE TYPE, CREATE JOB TO ow_billing;

EXIT;
