replicaCount: 1

image:
  repository: 599083837640.dkr.ecr.us-east-1.amazonaws.com/workshop/otterworks-analytics-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8088

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: analytics-service.otterworks.workshop.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: analytics-service-tls
      hosts:
        - analytics-service.otterworks.workshop.example.com

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheck:
  path: /health
  port: 8088

monitoring:
  enabled: true
  path: /metrics
  port: 8088

networkPolicy:
  enabled: true
  ingressNamespace: ingress-nginx
  monitoringNamespace: monitoring

serviceAccount:
  roleArn: ""
