# Front door: the API is closed by default. A Lambda authorizer (API-key style
# bearer token) guards every route except the unauthenticated GET /health probe.
#
# Why a Lambda authorizer rather than a Cognito user pool + JWT: the demo needs
# a deterministic, namespaced, zero-idle-cost credential the operator can paste
# into the demo page — not a user directory. The token is generated by Terraform
# (never committed) and surfaced only as a sensitive output; rotating it is one
# `terraform apply`.
#
# Gateway semantics with enable_simple_responses:
#   - missing Authorization header  -> API Gateway rejects with 401 (authorizer
#     is not even invoked; the header is the identity source)
#   - wrong credential              -> authorizer returns isAuthorized=false -> 403
#   - correct bearer token          -> route is invoked as before

resource "random_password" "demo_api_token" {
  length  = 40
  special = false
}

data "archive_file" "authorizer" {
  type        = "zip"
  source_file = "${path.module}/authorizer/authorizer.py"
  output_path = "${path.module}/authorizer/authorizer.zip"
}

resource "aws_iam_role" "authorizer" {
  name               = "${local.prefix}-authorizer-role"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

resource "aws_iam_role_policy" "authorizer" {
  name = "${local.prefix}-authorizer-policy"
  role = aws_iam_role.authorizer.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
      ]
      Resource = "arn:aws:logs:*:*:*"
    }]
  })
}

resource "aws_lambda_function" "authorizer" {
  function_name    = "${local.prefix}-authorizer"
  role             = aws_iam_role.authorizer.arn
  runtime          = "python3.12"
  handler          = "authorizer.handler"
  filename         = data.archive_file.authorizer.output_path
  source_code_hash = data.archive_file.authorizer.output_base64sha256
  memory_size      = 128
  timeout          = 5

  environment {
    variables = {
      PORTAL_API_TOKEN = random_password.demo_api_token.result
    }
  }
}

resource "aws_apigatewayv2_authorizer" "token" {
  api_id                            = aws_apigatewayv2_api.portal.id
  name                              = "${local.prefix}-token-authorizer"
  authorizer_type                   = "REQUEST"
  authorizer_uri                    = aws_lambda_function.authorizer.invoke_arn
  authorizer_payload_format_version = "2.0"
  enable_simple_responses           = true
  identity_sources                  = ["$request.header.Authorization"]
  # Cache decisions per Authorization header value so the authorizer Lambda is
  # not on the hot path of every request (and the load test measures the estate,
  # not the authorizer).
  authorizer_result_ttl_in_seconds = 300
}

resource "aws_lambda_permission" "authorizer" {
  statement_id  = "AllowAPIGatewayInvokeAuthorizer"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.authorizer.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.portal.execution_arn}/authorizers/${aws_apigatewayv2_authorizer.token.id}"
}
