CREATE TABLE announcement (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200)             NOT NULL,
    body       VARCHAR(4000)            NOT NULL,
    published  BOOLEAN                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Deliberate addition: the default listing filters on `published` and orders by `created_at`.
-- The monolith has no index at all here (ddl-auto only ever generated the primary key).
CREATE INDEX idx_announcement_published_created_at ON announcement (published, created_at DESC);
