using OtterWorks.ReportService.Models;
using OtterWorks.ReportService.Util;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace OtterWorks.ReportService.Services;

public class PdfReportGenerator : IPdfReportGenerator
{
    private readonly ILogger<PdfReportGenerator> _logger;

    public PdfReportGenerator(ILogger<PdfReportGenerator> logger)
    {
        _logger = logger;
    }

    public string GeneratePdf(Report report, List<Dictionary<string, object>> data, string outputDir)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var fileName = ReportDateUtils.BuildFileName(report.ReportName, "pdf");
        var outputPath = Path.Combine(outputDir, fileName);
        Directory.CreateDirectory(outputDir);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(36, Unit.Point);

                page.Header().Column(col =>
                {
                    col.Item().AlignCenter().Text("OtterWorks Report")
                        .FontSize(18).Bold().FontColor(Colors.Grey.Darken3);
                    col.Item().AlignCenter().Text(report.ReportName)
                        .FontSize(12).FontColor(Colors.Grey.Medium);
                    col.Item().AlignCenter().Text($"Period: {ReportDateUtils.ToDisplayString(report.DateFrom)} — {ReportDateUtils.ToDisplayString(report.DateTo)}")
                        .FontSize(12).FontColor(Colors.Grey.Medium);
                    col.Item().AlignCenter().Text($"Generated: {ReportDateUtils.ToDisplayString(DateTime.UtcNow)} | Rows: {data.Count}")
                        .FontSize(12).FontColor(Colors.Grey.Medium);
                    col.Item().PaddingBottom(20);
                });

                page.Content().Element(contentContainer =>
                {
                    if (data.Count == 0)
                    {
                        contentContainer.AlignCenter().Text("No data available for the selected criteria.")
                            .FontSize(12).FontColor(Colors.Grey.Medium);
                        return;
                    }

                    var columns = data[0].Keys.ToList();
                    contentContainer.Table(table =>
                    {
                        table.ColumnsDefinition(cd =>
                        {
                            foreach (var _ in columns)
                            {
                                cd.RelativeColumn();
                            }
                        });

                        foreach (var col in columns)
                        {
                            table.Cell().Background("#2C3E50").Padding(6).AlignCenter()
                                .Text(ReportDateUtils.FormatColumnName(col))
                                .FontSize(10).Bold().FontColor(Colors.White);
                        }

                        for (int rowIndex = 0; rowIndex < data.Count; rowIndex++)
                        {
                            var row = data[rowIndex];
                            var bgColor = rowIndex % 2 == 1 ? Color.FromHex("#ECF0F1") : Color.FromHex("#FFFFFF");
                            foreach (var col in columns)
                            {
                                var value = row.TryGetValue(col, out var v) ? v?.ToString() ?? "" : "";
                                table.Cell().Background(bgColor).Padding(4)
                                    .Text(value).FontSize(9);
                            }
                        }
                    });
                });

                page.Footer().AlignCenter()
                    .Text("This report was generated by OtterWorks Report Service v0.1.0. Data is subject to the reporting period specified above.")
                    .FontSize(8).Italic().FontColor(Colors.Grey.Medium);
            });
        });

        document.GeneratePdf(outputPath);
        var fileInfo = new FileInfo(outputPath);
        _logger.LogInformation("Generated PDF report: {Path} ({Bytes} bytes)", outputPath, fileInfo.Length);
        return outputPath;
    }
}
