using System.Globalization;
using OtterWorks.ReportService.Models;
using OtterWorks.ReportService.Utilities;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
namespace OtterWorks.ReportService.Services;

public class PdfReportGenerator : IPdfReportGenerator
{
    private readonly ILogger<PdfReportGenerator> _logger;

    public PdfReportGenerator(ILogger<PdfReportGenerator> logger)
    {
        _logger = logger;
    }

    public string GeneratePdf(Report report, List<Dictionary<string, object>> data, string outputDir)
    {
        string fileName = BuildFileName(report, "pdf");
        string filePath = Path.Combine(outputDir, fileName);
        Directory.CreateDirectory(outputDir);

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape());
                page.Margin(36);

                page.Header().Column(col =>
                {
                    col.Item().AlignCenter().Text("OtterWorks Report")
                        .FontSize(18).Bold().FontColor(Colors.Grey.Darken3);

                    col.Item().AlignCenter().Text(report.ReportName)
                        .FontSize(12).FontColor(Colors.Grey.Medium);

                    col.Item().AlignCenter().Text($"Period: {ReportDateUtils.ToDisplayString(report.DateFrom)} — {ReportDateUtils.ToDisplayString(report.DateTo)}")
                        .FontSize(12).FontColor(Colors.Grey.Medium);

                    col.Item().AlignCenter().Text($"Generated: {ReportDateUtils.ToDisplayString(DateTime.UtcNow)} | Rows: {data.Count}")
                        .FontSize(12).FontColor(Colors.Grey.Medium);

                    col.Item().PaddingBottom(20);
                });

                page.Content().Element(contentContainer =>
                {
                    if (data.Count == 0)
                    {
                        contentContainer.AlignCenter().Text("No data available for the selected criteria.")
                            .FontSize(12).FontColor(Colors.Grey.Medium);
                        return;
                    }

                    var columns = data[0].Keys.ToList();
                    contentContainer.Table(table =>
                    {
                        table.ColumnsDefinition(cd =>
                        {
                            foreach (var _ in columns)
                            {
                                cd.RelativeColumn();
                            }
                        });

                        foreach (string col in columns)
                        {
                            table.Cell().Background("#2C3E50").Padding(6).AlignCenter()
                                .Text(FormatColumnName(col)).FontSize(10).Bold().FontColor(Colors.White);
                        }

                        for (int rowIdx = 0; rowIdx < data.Count; rowIdx++)
                        {
                            string bgColor = rowIdx % 2 == 1 ? "#ECF0F1" : "#FFFFFF";
                            foreach (string col in columns)
                            {
                                string cellValue = data[rowIdx].TryGetValue(col, out var val) && val != null
                                    ? Convert.ToString(val, CultureInfo.InvariantCulture) ?? string.Empty
                                    : string.Empty;
                                table.Cell().Background(bgColor).Padding(4)
                                    .Text(cellValue).FontSize(9);
                            }
                        }
                    });
                });

                page.Footer().AlignCenter().Text(
                    "This report was generated by OtterWorks Report Service v0.1.0. Data is subject to the reporting period specified above.")
                    .FontSize(8).Italic().FontColor(Colors.Grey.Medium);
            });
        });

        document.GeneratePdf(filePath);

        _logger.LogInformation("Generated PDF report: {FilePath} ({Size} bytes)", filePath, new FileInfo(filePath).Length);
        return filePath;
    }

    private static string FormatColumnName(string columnName)
    {
        if (string.IsNullOrWhiteSpace(columnName))
        {
            return string.Empty;
        }

        string replaced = columnName.Replace("_", " ");
        return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(replaced);
    }

    private static string BuildFileName(Report report, string extension)
    {
        string safeName = System.Text.RegularExpressions.Regex.Replace(report.ReportName, "[^a-zA-Z0-9]", "_").ToLowerInvariant();
        return $"{safeName}_{ReportDateUtils.ToFileNameString(DateTime.UtcNow)}.{extension}";
    }
}
