apiVersion: v1
kind: Secret
metadata:
  name: analytics-dw-credentials
  namespace: legacy-dw
  labels:
    app.kubernetes.io/name: analytics-dw
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: dw_admin
  POSTGRES_PASSWORD: dw_local_dev
  POSTGRES_DB: analytics_dw
