replicaCount: 1

image:
  repository: 599083837640.dkr.ecr.us-east-1.amazonaws.com/workshop/otterworks-web-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: web-app.otterworks.workshop.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: web-app-tls
      hosts:
        - web-app.otterworks.workshop.example.com

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheck:
  path: /health
  port: 3000

monitoring:
  enabled: true
  path: /metrics
  port: 3000

networkPolicy:
  enabled: true
  ingressNamespace: ingress-nginx
  monitoringNamespace: monitoring
