-- ARCHIVE.RETNPLCY: retention policy lookup (40 rows). Record layout: RETNPLCY.cpy, LRECL 128.

CREATE TABLE ARCHIVE.RETNPLCY (
    POLICY_CODE         CHAR(4)        NOT NULL,
    POLICY_DESC         CHAR(60)       NOT NULL,
    RETENTION_YEARS     SMALLINT       NOT NULL,
    SUCCESSOR_CODE      CHAR(4)        NOT NULL,
    ACTIVE_FLAG         CHAR(1)        NOT NULL,
    DISPOSITION_ACTION  CHAR(4)        NOT NULL,
    EFFECTIVE_TS        TIMESTAMP(12)  NOT NULL,
    CONSTRAINT PK_RETNPLCY PRIMARY KEY (POLICY_CODE),
    CONSTRAINT CK_RETNPLCY_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CONSTRAINT CK_RETNPLCY_ACTION CHECK (DISPOSITION_ACTION IN ('DEST', 'REVW', 'PERM'))
) ORGANIZE BY ROW;
