-- ARCHIVE.DOCARCH: archived document versions (1,200,000 rows). Record layout: DOCARCH.cpy, LRECL 256.
-- OWNER_NAME and DISPOSITION_DT hold EBCDIC CCSID 037 bytes (FOR BIT DATA: Db2 performs no conversion).

CREATE TABLE ARCHIVE.DOCARCH (
    ARCH_KEY            CHAR(16)                 NOT NULL,
    DOC_ID              CHAR(36)                 NOT NULL,
    VERSION_NO          SMALLINT                 NOT NULL,
    RETENTION_CLASS     CHAR(4)                  NOT NULL,
    LAST_ACCESS_TS      TIMESTAMP(12)            NOT NULL,
    STORAGE_CHARGE      DECIMAL(31, 8)           NOT NULL,
    UNIT_RATE           DECIMAL(31, 8)           NOT NULL,
    OWNER_NAME          CHAR(40) FOR BIT DATA    NOT NULL,
    DISPOSITION_DT      CHAR(8) FOR BIT DATA     NOT NULL,
    LEGAL_HOLD_FLAG     CHAR(1)                  NOT NULL,
    CHECKSUM_ALG        CHAR(8)                  NOT NULL,
    CONTENT_SHA256      CHAR(64)                 NOT NULL,
    BYTE_SIZE           BIGINT                   NOT NULL,
    SOURCE_SYS          CHAR(3)                  NOT NULL,
    CONSTRAINT PK_DOCARCH PRIMARY KEY (ARCH_KEY),
    CONSTRAINT FK_DOCARCH_RETNPLCY FOREIGN KEY (RETENTION_CLASS)
        REFERENCES ARCHIVE.RETNPLCY (POLICY_CODE) ON DELETE RESTRICT,
    CONSTRAINT CK_DOCARCH_HOLD CHECK (LEGAL_HOLD_FLAG IN ('Y', 'N'))
) ORGANIZE BY ROW;

CREATE INDEX ARCHIVE.IX_DOCARCH_SEL ON ARCHIVE.DOCARCH (RETENTION_CLASS, LAST_ACCESS_TS);
