-- ARCHIVE.FILEAUD: access/disposition events (4,100,000 rows). Record layout: FILEAUD.cpy, LRECL 160.
-- RETENTION_CLASS is denormalized from the parent DOCARCH row at event time.

CREATE TABLE ARCHIVE.FILEAUD (
    AUDIT_KEY           CHAR(20)       NOT NULL,
    ARCH_KEY            CHAR(16)       NOT NULL,
    EVENT_TYPE          CHAR(4)        NOT NULL,
    EVENT_TS            TIMESTAMP(12)  NOT NULL,
    ACTOR_ID            CHAR(12)       NOT NULL,
    RETENTION_CLASS     CHAR(4)        NOT NULL,
    DISPOSITION_CODE    CHAR(2)        NOT NULL,
    CLIENT_IP           CHAR(15)       NOT NULL,
    DETAIL_TEXT         CHAR(40)       NOT NULL,
    CONSTRAINT PK_FILEAUD PRIMARY KEY (AUDIT_KEY),
    CONSTRAINT FK_FILEAUD_DOCARCH FOREIGN KEY (ARCH_KEY)
        REFERENCES ARCHIVE.DOCARCH (ARCH_KEY) ON DELETE RESTRICT,
    CONSTRAINT CK_FILEAUD_EVENT CHECK (EVENT_TYPE IN ('VIEW', 'DNLD', 'HOLD', 'RLSE', 'DISP', 'XPRT'))
) ORGANIZE BY ROW;

CREATE INDEX ARCHIVE.IX_FILEAUD_PARENT ON ARCHIVE.FILEAUD (ARCH_KEY);
CREATE INDEX ARCHIVE.IX_FILEAUD_SEL ON ARCHIVE.FILEAUD (RETENTION_CLASS, EVENT_TS);
