CREATE TABLE feedback (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(100)                NOT NULL,
    rating     INTEGER                     NOT NULL,
    message    VARCHAR(2000)               NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Deliberate addition: `findByUserIdOrderByCreatedAtDesc` is a full table scan in the monolith,
-- which has no index beyond the primary key. Flagged High in the assessment.
CREATE INDEX idx_feedback_user_id_created_at ON feedback (user_id, created_at DESC);
