-- ARCHIVE.RETNPLCY: retention policy lookup (40 rows). Logical layout: RETNPLCY.cpy, LRECL 128.
-- Db2 -> Oracle: SMALLINT -> NUMBER(5), TIMESTAMP(12) -> TIMESTAMP(9) (Oracle's maximum fraction).
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE ARCHIVE.RETNPLCY (
    POLICY_CODE         CHAR(4)        NOT NULL,
    POLICY_DESC         VARCHAR2(60)   NOT NULL,
    RETENTION_YEARS     NUMBER(5)      NOT NULL,
    SUCCESSOR_CODE      CHAR(4)        NOT NULL,
    ACTIVE_FLAG         CHAR(1)        NOT NULL,
    DISPOSITION_ACTION  CHAR(4)        NOT NULL,
    EFFECTIVE_TS        TIMESTAMP(9)   NOT NULL,
    CONSTRAINT PK_RETNPLCY PRIMARY KEY (POLICY_CODE),
    CONSTRAINT CK_RETNPLCY_ACTIVE CHECK (ACTIVE_FLAG IN ('Y', 'N')),
    CONSTRAINT CK_RETNPLCY_ACTION CHECK (DISPOSITION_ACTION IN ('DEST', 'REVW', 'PERM'))
);
