-- MIGAUDIT.PURGE_AUDIT: one row per source key deleted by PURGE, inserted in the SAME transaction
-- and BEFORE the DELETE of that key (CONTRACTS.md §9.4). Never purged, never migrated.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE TABLE MIGAUDIT.PURGE_AUDIT (
    RUN_ID              VARCHAR2(64)   NOT NULL,
    TABLE_NAME          VARCHAR2(128)  NOT NULL,
    SOURCE_KEY          VARCHAR2(64)   NOT NULL,
    PURGED_AT           TIMESTAMP(9)   DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PURGE_AUDIT PRIMARY KEY (RUN_ID, TABLE_NAME, SOURCE_KEY)
);
