#!/usr/bin/env bash
set -euo pipefail

# trivy-issues.sh — Run Trivy SAST scan and create idempotent GitHub issues
# for each vulnerability, labeled with "trivy" and "sast".
#
# Usage:
#   ./scripts/trivy-issues.sh [OPTIONS]
#
# Options:
#   --dry-run         Print what would be created without actually creating issues
#   --input FILE      Use an existing Trivy JSON file instead of running a scan
#   --severity LIST   Comma-separated severities (default: CRITICAL,HIGH)
#   --skip-dirs DIRS  Comma-separated dirs to skip (default: services/report-service)
#   --repo OWNER/REPO GitHub repository (default: auto-detected via gh)
#
# Requirements: trivy, gh (authenticated), jq

SEVERITY="CRITICAL,HIGH"
SKIP_DIRS="services/report-service"
DRY_RUN=false
INPUT_FILE=""
REPO=""
LABELS="trivy,sast"

usage() {
  sed -n '3,14p' "$0" | sed 's/^# \?//'
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)    DRY_RUN=true; shift ;;
    --input)      INPUT_FILE="$2"; shift 2 ;;
    --severity)   SEVERITY="$2"; shift 2 ;;
    --skip-dirs)  SKIP_DIRS="$2"; shift 2 ;;
    --repo)       REPO="$2"; shift 2 ;;
    --help|-h)    usage ;;
    *)            echo "Unknown option: $1"; usage ;;
  esac
done

# Resolve repo
if [[ -z "$REPO" ]]; then
  REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || true)
  if [[ -z "$REPO" ]]; then
    echo "ERROR: Could not detect repository. Pass --repo OWNER/REPO." >&2
    exit 1
  fi
fi

echo "Repository: $REPO"
echo "Labels:     $LABELS"
echo "Severity:   $SEVERITY"
echo "Dry run:    $DRY_RUN"
echo "---"

# Step 1: Get Trivy JSON results
RESULTS_FILE=""
if [[ -n "$INPUT_FILE" ]]; then
  if [[ ! -f "$INPUT_FILE" ]]; then
    echo "ERROR: Input file not found: $INPUT_FILE" >&2
    exit 1
  fi
  RESULTS_FILE="$INPUT_FILE"
  echo "Using existing Trivy results: $INPUT_FILE"
else
  RESULTS_FILE=$(mktemp /tmp/trivy-results-XXXXXX.json)
  trap 'rm -f "$RESULTS_FILE"' EXIT

  echo "Running Trivy filesystem scan..."
  trivy fs . \
    --severity "$SEVERITY" \
    --format json \
    --output "$RESULTS_FILE" \
    --skip-dirs "$SKIP_DIRS" \
    --ignorefile .trivyignore \
    --scanners vuln \
    --quiet \
    || true

  echo "Scan complete: $RESULTS_FILE"
fi

# Step 2: Extract unique vulnerabilities (dedup by CVE+package+target)
VULNS_JSON=$(jq -c '
  [.Results[]? |
    select((.Vulnerabilities // []) | length > 0) |
    .Target as $target |
    .Vulnerabilities[] |
    {
      id: .VulnerabilityID,
      pkg: .PkgName,
      installed: .InstalledVersion,
      fixed: (.FixedVersion // "n/a"),
      severity: .Severity,
      title: (.Title // "No description"),
      target: $target,
      refs: ([.References[]?] | first // ""),
      description: (.Description // "No description available.")
    }
  ] | unique_by(.id + "|" + .pkg + "|" + .target)
' "$RESULTS_FILE")

VULN_COUNT=$(echo "$VULNS_JSON" | jq 'length')
echo "Found $VULN_COUNT unique vulnerabilities."
echo ""

if [[ "$VULN_COUNT" -eq 0 ]]; then
  echo "No vulnerabilities to report. Exiting."
  exit 0
fi

# Step 3: Ensure labels exist
if [[ "$DRY_RUN" == "false" ]]; then
  for label in trivy sast; do
    gh label create "$label" --repo "$REPO" --color "d93f0b" --force 2>/dev/null || true
  done
fi

# Step 4: Fetch all existing open issues with "trivy" label to check idempotency
echo "Fetching existing issues with label 'trivy'..."
EXISTING_TITLES=$(gh issue list --repo "$REPO" --label "trivy" --state open --limit 500 --json title -q '.[].title')

# Step 5: Create issues for each vulnerability
CREATED=0
SKIPPED=0

while IFS= read -r vuln; do
  VULN_ID=$(echo "$vuln" | jq -r '.id')
  PKG=$(echo "$vuln" | jq -r '.pkg')
  TARGET=$(echo "$vuln" | jq -r '.target')
  INSTALLED=$(echo "$vuln" | jq -r '.installed')
  FIXED=$(echo "$vuln" | jq -r '.fixed')
  SEV=$(echo "$vuln" | jq -r '.severity')
  TITLE_DESC=$(echo "$vuln" | jq -r '.title')
  DESCRIPTION=$(echo "$vuln" | jq -r '.description')
  REF=$(echo "$vuln" | jq -r '.refs')

  # Issue title is the idempotency key
  ISSUE_TITLE="[Trivy SAST] ${VULN_ID}: ${PKG} (${TARGET})"

  # Check if issue already exists
  if echo "$EXISTING_TITLES" | grep -qF "$ISSUE_TITLE"; then
    echo "SKIP (exists): $ISSUE_TITLE"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # Build issue body
  ISSUE_BODY="## Trivy SAST Vulnerability

| Field | Value |
|-------|-------|
| **CVE / Advisory** | \`${VULN_ID}\` |
| **Severity** | ${SEV} |
| **Package** | \`${PKG}\` |
| **Installed Version** | \`${INSTALLED}\` |
| **Fixed Version** | \`${FIXED}\` |
| **Target File** | \`${TARGET}\` |

### Summary

${TITLE_DESC}

### Description

${DESCRIPTION}

### References

${REF:+- ${REF}}

---
_Auto-generated by \`scripts/trivy-issues.sh\`. Do not edit the title — it is used for idempotency._"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "DRY-RUN: Would create issue: $ISSUE_TITLE"
  else
    gh issue create \
      --repo "$REPO" \
      --title "$ISSUE_TITLE" \
      --body "$ISSUE_BODY" \
      --label "trivy" \
      --label "sast"
    echo "CREATED: $ISSUE_TITLE"
  fi

  CREATED=$((CREATED + 1))
done < <(echo "$VULNS_JSON" | jq -c '.[]')

echo ""
echo "--- Summary ---"
echo "Total vulnerabilities: $VULN_COUNT"
if [[ "$DRY_RUN" == "true" ]]; then
  echo "Would create: $CREATED"
else
  echo "Created: $CREATED"
fi
echo "Skipped (already exist): $SKIPPED"
