-- Fulfilment context extracted from the BoxOffice monolith (schema.sql L238-L258).
-- order_id -> order_ref (the order lives in the orders service); order_item_id -> seat_inventory_id + order_ref.

CREATE TABLE tickets (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code       VARCHAR(32)  NOT NULL UNIQUE,
  order_ref         VARCHAR(32)  NOT NULL,
  seat_inventory_id BIGINT       NOT NULL,
  barcode           VARCHAR(64)  NOT NULL,
  issued_at         TIMESTAMP    NOT NULL DEFAULT now(),
  scanned_at        TIMESTAMP,
  CONSTRAINT tickets_order_seat_uq UNIQUE (order_ref, seat_inventory_id)
);
CREATE INDEX tickets_order_ref_idx ON tickets (order_ref);

-- written in the inbox transaction, mailed later by an ops cron (never in this demo: status stays QUEUED)
CREATE TABLE confirmations (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ref      VARCHAR(32)  NOT NULL UNIQUE,
  hold_ref       VARCHAR(32),
  performance_id BIGINT       NOT NULL,
  channel        VARCHAR(8)   NOT NULL DEFAULT 'EMAIL',
  recipient      VARCHAR(160) NOT NULL,
  subject        VARCHAR(200) NOT NULL,
  body           TEXT         NOT NULL,
  status         VARCHAR(16)  NOT NULL DEFAULT 'QUEUED',
  sent_at        TIMESTAMP,
  created_at     TIMESTAMP    NOT NULL DEFAULT now()
);
