"""Renders fixtures/mig06_prior_run*.sql: the partially completed prior run that makes MIG-06 fail (SEED-SPEC.md §8).

One rendering per target provider: T-SQL for Azure SQL (mig06_prior_run.sql), PL/pgSQL for PostgreSQL
(mig06_prior_run.postgresql.sql) and Snowflake SQL (mig06_prior_run.snowflake.sql). All plant the same rows.
The Snowflake rendering carries only the five STG.DOCARCH rows: with a split target the control-plane part
(ABANDONED run, stale key range) is the PostgreSQL fixture, applied to the control plane by the same `ldm init`.
"""

from __future__ import annotations

from typing import Literal

from . import tables
from .spec import decimal8

Dialect = Literal["azuresql", "postgresql", "snowflake"]
DIALECTS: tuple[Dialect, ...] = ("azuresql", "postgresql", "snowflake")

HEADER = """\
-- MIG-06 prior-run fixture (SEED-SPEC.md §8). GENERATED by `python3.12 -m seed --fixture-out`; do not edit.
-- Simulates a partially completed earlier migration run: an ABANDONED mig.runs row, a stale
-- mig.key_ranges row whose LOAD never finished, and the five staging rows it left behind. The
-- unique index UX_stg_DOCARCH_source_key (namespace, source_key) then rejects the real run's
-- MIG06-* rows with SQL Server error 2601 / SQLSTATE 23000 -> rule DUPLICATE_SOURCE_KEY.
-- Idempotent. Namespace comes from SESSION_CONTEXT(N'ldm.namespace') (set by `ldm init --apply-sql`).
SET NOCOUNT ON;
DECLARE @ns NVARCHAR(32) = CONVERT(NVARCHAR(32), SESSION_CONTEXT(N'ldm.namespace'));
IF @ns IS NULL THROW 50001, N'SESSION_CONTEXT ldm.namespace is not set', 1;
DECLARE @run NVARCHAR(64) = N'prior-partial';

IF NOT EXISTS (SELECT 1 FROM mig.runs WHERE run_id = @run AND namespace = @ns)
INSERT INTO mig.runs (run_id, namespace, status, purge_enabled, started_at, finished_at)
VALUES (@run, @ns, N'ABANDONED', 0, '2026-01-01T00:00:00', NULL);

IF NOT EXISTS (SELECT 1 FROM mig.key_ranges WHERE run_id = @run AND namespace = @ns AND table_name = N'DOCARCH' AND range_seq = 1)
INSERT INTO mig.key_ranges (run_id, namespace, table_name, range_seq, key_from, key_to, rows_extracted,
                            extract_status, load_status, extracted_at)
VALUES (@run, @ns, N'DOCARCH', 1, N'MIG06-0000000001', N'MIG06-0000000005', 5, N'DONE', N'RUNNING', '2026-01-01T00:05:00');
"""

ROW = """
IF NOT EXISTS (SELECT 1 FROM stg.DOCARCH WHERE namespace = @ns AND source_key = N'{key}')
INSERT INTO stg.DOCARCH (run_id, namespace, source_key, range_seq, batch_id, raw_bytes, row_hash,
    ARCH_KEY, DOC_ID, VERSION_NO, RETENTION_CLASS, LAST_ACCESS_TS, LAST_ACCESS_TS_NANOS_TAIL,
    STORAGE_CHARGE, UNIT_RATE, OWNER_NAME, DISPOSITION_DT, LEGAL_HOLD_FLAG, CHECKSUM_ALG,
    CONTENT_SHA256, BYTE_SIZE, SOURCE_SYS)
VALUES (@run, @ns, N'{key}', 1, 1, 0x{raw}, NULL,
    N'{key}', N'{doc_id}', {version}, N'{cls}', '{ts7}', {tail},
    {charge}, {rate}, N'{owner}', '{disp}', N'{hold}', N'{alg}',
    N'{sha}', {size}, N'{src}');
"""

PG_HEADER = """\
-- MIG-06 prior-run fixture (SEED-SPEC.md §8). GENERATED by
-- `python3.12 -m seed --fixture-out <file> --fixture-dialect postgresql`; do not edit.
-- Simulates a partially completed earlier migration run: an ABANDONED mig.runs row, a stale
-- mig.key_ranges row whose LOAD never finished, and the five staging rows it left behind. The
-- unique index ux_stg_docarch_source_key (namespace, source_key) then rejects the real run's
-- MIG06-* rows with SQLSTATE 23505 -> rule DUPLICATE_SOURCE_KEY.
-- Idempotent. Namespace comes from current_setting('ldm.namespace') (set by `ldm init --apply-sql`).
DO $fixture$
DECLARE
    ns  VARCHAR(32) := current_setting('ldm.namespace', true);
    run VARCHAR(64) := 'prior-partial';
BEGIN
    IF ns IS NULL OR ns = '' THEN
        RAISE EXCEPTION 'ldm.namespace is not set';
    END IF;

    INSERT INTO mig.runs (run_id, namespace, status, purge_enabled, started_at, finished_at)
    VALUES (run, ns, 'ABANDONED', false, TIMESTAMP '2026-01-01 00:00:00', NULL)
    ON CONFLICT DO NOTHING;

    INSERT INTO mig.key_ranges (run_id, namespace, table_name, range_seq, key_from, key_to, rows_extracted,
                                extract_status, load_status, extracted_at)
    VALUES (run, ns, 'DOCARCH', 1, 'MIG06-0000000001', 'MIG06-0000000005', 5, 'DONE', 'RUNNING',
            TIMESTAMP '2026-01-01 00:05:00')
    ON CONFLICT DO NOTHING;
"""

PG_ROW = """
    INSERT INTO stg."DOCARCH" (run_id, namespace, source_key, range_seq, batch_id, raw_bytes, row_hash,
        "ARCH_KEY", "DOC_ID", "VERSION_NO", "RETENTION_CLASS", "LAST_ACCESS_TS", "LAST_ACCESS_TS_NANOS_TAIL",
        "STORAGE_CHARGE", "UNIT_RATE", "OWNER_NAME", "DISPOSITION_DT", "LEGAL_HOLD_FLAG", "CHECKSUM_ALG",
        "CONTENT_SHA256", "BYTE_SIZE", "SOURCE_SYS")
    VALUES (run, ns, '{key}', 1, 1, '\\x{raw}'::bytea, NULL,
        '{key}', '{doc_id}', {version}, '{cls}', TIMESTAMP '{ts6}', {tail6},
        {charge}, {rate}, '{owner}', DATE '{disp}', '{hold}', '{alg}',
        '{sha}', {size}, '{src}')
    ON CONFLICT DO NOTHING;
"""

PG_FOOTER = "END\n$fixture$;\n"

SF_HEADER = """\
-- MIG-06 prior-run fixture, Snowflake archive store (SEED-SPEC.md §8). GENERATED by
-- `python3.12 -m seed --fixture-out <file> --fixture-dialect snowflake`; do not edit.
-- The five STG.DOCARCH rows a partially completed earlier run left behind (its ABANDONED mig.runs row and
-- stale mig.key_ranges row live in the PostgreSQL control plane: mig06_prior_run.postgresql.sql). The driver's
-- cross-run duplicate check after COPY INTO then rejects the real run's MIG06-* rows with SQLSTATE 23505
-- -> rule DUPLICATE_SOURCE_KEY. Idempotent. Namespace comes from the session variable $LDM_NAMESPACE
-- (set by `ldm init --apply-archive-sql`).
SELECT IFF($LDM_NAMESPACE IS NULL OR $LDM_NAMESPACE = '', 1 / 0, 1) AS namespace_is_set;
"""

SF_ROW = """
INSERT INTO STG.DOCARCH (RUN_ID, NAMESPACE, SOURCE_KEY, RANGE_SEQ, BATCH_ID, RAW_BYTES, LOADED_AT,
    ARCH_KEY, DOC_ID, VERSION_NO, RETENTION_CLASS, LAST_ACCESS_TS, LAST_ACCESS_TS_NANOS_TAIL,
    STORAGE_CHARGE, UNIT_RATE, OWNER_NAME, DISPOSITION_DT, LEGAL_HOLD_FLAG, CHECKSUM_ALG,
    CONTENT_SHA256, BYTE_SIZE, SOURCE_SYS)
SELECT 'prior-partial', $LDM_NAMESPACE, '{key}', 1, 1, TO_BINARY('{raw}', 'HEX'), '2026-01-01 00:05:00'::TIMESTAMP_NTZ,
    '{key}', '{doc_id}', {version}, '{cls}', '{ts6}'::TIMESTAMP_NTZ, {tail6},
    {charge}, {rate}, '{owner}', DATE '{disp}', '{hold}', '{alg}',
    '{sha}', {size}, '{src}'
FROM (SELECT 1) AS one
WHERE NOT EXISTS (SELECT 1 FROM STG.DOCARCH WHERE NAMESPACE = $LDM_NAMESPACE AND SOURCE_KEY = '{key}');
"""


def _planted_rows() -> list[dict[str, str | int]]:
    rows: list[dict[str, str | int]] = []
    for tag, row in tables.planted_docarch():
        if tag != "MIG-06":
            continue
        key = row.arch_key.decode("ascii").rstrip()
        ts = row.last_access_ts  # YYYY-MM-DD-HH.MM.SS.NNNNNNNNNNNN
        hms = f"{ts[0:10]} {ts[11:13]}:{ts[14:16]}:{ts[17:19]}"
        disp = row.disposition_dt.decode("cp037")
        rows.append(dict(
            key=key, raw=row.record().hex().upper(), doc_id=row.doc_id, version=row.version_no,
            cls=row.retention_class,
            # Azure SQL: DATETIME2(7) + 5-digit tail; PostgreSQL: TIMESTAMP(6) + 6-digit tail (drivers/postgresql.py)
            ts7=f"{hms}.{ts[20:27]}", tail=int(ts[27:32]), ts6=f"{hms}.{ts[20:26]}", tail6=int(ts[26:32]),
            charge=decimal8(row.storage_charge),
            rate=decimal8(row.unit_rate), owner=row.owner_name.decode("cp037").rstrip(),
            disp=f"{disp[0:4]}-{disp[4:6]}-{disp[6:8]}", hold=row.legal_hold_flag,
            alg=row.checksum_alg, sha=row.content_sha256, size=row.byte_size, src=row.source_sys,
        ))
    return rows


def render(dialect: Dialect = "azuresql") -> str:
    if dialect == "postgresql":
        header, row_tpl, footer = PG_HEADER, PG_ROW, PG_FOOTER
    elif dialect == "snowflake":
        header, row_tpl, footer = SF_HEADER, SF_ROW, ""
    else:
        header, row_tpl, footer = HEADER, ROW, "GO\n"
    parts = [header]
    for row in _planted_rows():
        parts.append(row_tpl.format(**row))
    parts.append(footer)
    return "".join(parts)
