"""Renders fixtures/mig06_prior_run.sql: the partially completed prior run that makes MIG-06 fail (SEED-SPEC.md §8)."""

from __future__ import annotations

from . import tables
from .spec import decimal8

HEADER = """\
-- MIG-06 prior-run fixture (SEED-SPEC.md §8). GENERATED by `python3.12 -m seed --fixture-out`; do not edit.
-- Simulates a partially completed earlier migration run: an ABANDONED mig.runs row, a stale
-- mig.key_ranges row whose LOAD never finished, and the five staging rows it left behind. The
-- unique index UX_stg_DOCARCH_source_key (namespace, source_key) then rejects the real run's
-- MIG06-* rows with SQL Server error 2601 / SQLSTATE 23000 -> rule DUPLICATE_SOURCE_KEY.
-- Idempotent. Namespace comes from SESSION_CONTEXT(N'ldm.namespace') (set by `ldm init --apply-sql`).
SET NOCOUNT ON;
DECLARE @ns NVARCHAR(32) = CONVERT(NVARCHAR(32), SESSION_CONTEXT(N'ldm.namespace'));
IF @ns IS NULL THROW 50001, N'SESSION_CONTEXT ldm.namespace is not set', 1;
DECLARE @run NVARCHAR(64) = N'prior-partial';

IF NOT EXISTS (SELECT 1 FROM mig.runs WHERE run_id = @run AND namespace = @ns)
INSERT INTO mig.runs (run_id, namespace, status, purge_enabled, started_at, finished_at)
VALUES (@run, @ns, N'ABANDONED', 0, '2026-01-01T00:00:00', NULL);

IF NOT EXISTS (SELECT 1 FROM mig.key_ranges WHERE run_id = @run AND namespace = @ns AND table_name = N'DOCARCH' AND range_seq = 1)
INSERT INTO mig.key_ranges (run_id, namespace, table_name, range_seq, key_from, key_to, rows_extracted,
                            extract_status, load_status, extracted_at)
VALUES (@run, @ns, N'DOCARCH', 1, N'MIG06-0000000001', N'MIG06-0000000005', 5, N'DONE', N'RUNNING', '2026-01-01T00:05:00');
"""

ROW = """
IF NOT EXISTS (SELECT 1 FROM stg.DOCARCH WHERE namespace = @ns AND source_key = N'{key}')
INSERT INTO stg.DOCARCH (run_id, namespace, source_key, range_seq, batch_id, raw_bytes, row_hash,
    ARCH_KEY, DOC_ID, VERSION_NO, RETENTION_CLASS, LAST_ACCESS_TS, LAST_ACCESS_TS_NANOS_TAIL,
    STORAGE_CHARGE, UNIT_RATE, OWNER_NAME, DISPOSITION_DT, LEGAL_HOLD_FLAG, CHECKSUM_ALG,
    CONTENT_SHA256, BYTE_SIZE, SOURCE_SYS)
VALUES (@run, @ns, N'{key}', 1, 1, 0x{raw}, NULL,
    N'{key}', N'{doc_id}', {version}, N'{cls}', '{ts7}', {tail},
    {charge}, {rate}, N'{owner}', '{disp}', N'{hold}', N'{alg}',
    N'{sha}', {size}, N'{src}');
"""


def render() -> str:
    parts = [HEADER]
    for tag, row in tables.planted_docarch():
        if tag != "MIG-06":
            continue
        key = row.arch_key.decode("ascii").rstrip()
        ts = row.last_access_ts  # YYYY-MM-DD-HH.MM.SS.NNNNNNNNNNNN
        ts7 = f"{ts[0:10]} {ts[11:13]}:{ts[14:16]}:{ts[17:19]}.{ts[20:27]}"
        tail = int(ts[27:32])
        disp = row.disposition_dt.decode("cp037")
        parts.append(ROW.format(
            key=key, raw=row.record().hex().upper(), doc_id=row.doc_id, version=row.version_no,
            cls=row.retention_class, ts7=ts7, tail=tail, charge=decimal8(row.storage_charge),
            rate=decimal8(row.unit_rate), owner=row.owner_name.decode("cp037").rstrip(),
            disp=f"{disp[0:4]}-{disp[4:6]}-{disp[6:8]}", hold=row.legal_hold_flag,
            alg=row.checksum_alg, sha=row.content_sha256, size=row.byte_size, src=row.source_sys,
        ))
    parts.append("GO\n")
    return "".join(parts)
