// Code generated by observability/slo/generate.py from observability/slo/critical-apis.yaml
// DO NOT EDIT. Run `make slo-generate` after changing the catalog.

package middleware

// criticalRoutes are the endpoints under an SLO. Requests matching one of
// these are labelled with the route template so a single failing endpoint is
// visible instead of being averaged into its service prefix. Everything else
// falls back to the prefix label, which keeps metric cardinality bounded.
var criticalRoutes = []routePattern{
	{method: "POST", template: "/api/v1/auth/login", service: "auth-service"},
	{method: "GET", template: "/api/v1/auth/profile", service: "auth-service"},
	{method: "POST", template: "/api/v1/auth/refresh", service: "auth-service"},
	{method: "GET", template: "/api/v1/collab/documents/{id}/presence", service: "collab-service"},
	{method: "GET", template: "/api/v1/documents", service: "document-service"},
	{method: "POST", template: "/api/v1/documents", service: "document-service"},
	{method: "GET", template: "/api/v1/documents/{id}", service: "document-service"},
	{method: "PUT", template: "/api/v1/documents/{id}", service: "document-service"},
	{method: "GET", template: "/api/v1/documents/{id}/export", service: "document-service"},
	{method: "GET", template: "/api/v1/files", service: "file-service"},
	{method: "POST", template: "/api/v1/files/upload", service: "file-service"},
	{method: "GET", template: "/api/v1/files/{id}/download", service: "file-service"},
	{method: "GET", template: "/api/v1/notifications", service: "notification-service"},
	{method: "GET", template: "/api/v1/search", service: "search-service"},
}
